# Generated by Django 5.2.3 on 2025-06-26 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_studentfaceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfaceimage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='students.studentprofile'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
