# Generated by Django 5.2.3 on 2025-07-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentfaceimage_student_delete_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentfaceimage',
            unique_together=set(),
        ),
    ]
